/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cadEuroChem;

import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import cadEuroChem.MultiPainel;
import javax.swing.JOptionPane;
/**
 *
 * @author phsto
 */
public class MultiPainel extends javax.swing.JFrame {
    private ArrayList<Fornecedor> fornecedores = new ArrayList<>();
    private LoginJFrame loginJFrame;

    public MultiPainel(LoginJFrame loginFrame) {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        // COLOCAR O ÍCONE DO PROGRAMA NO CANTO DA PÁGINA
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/cadEuroChem/img/logoIcon.png")));
        this.loginJFrame = loginFrame; // Armazene a referência para uso posterior
        buttonCadastrarUsuario.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Código para abrir a janela de cadastro (SingupJFrame)
                SingupJFrame singupFrame = new SingupJFrame();
                singupFrame.setVisible(true);
            }
        });
    }
    public Fornecedor getCadastroFornecedor(){
        String auxNameFornecedor = campoNameFornecedor.getText(); // Obtém o valor do campo de nome
        int auxNumFornecedor = Integer.parseInt(campoNumeroFornecedor.getText()); // Obtém o valor do campo de número
        String auxCNPJ = campoCnpjFornecedor.getText();
        String auxEmissao = campoDataEmissao.getText();
        String auxRecebimento = campoDataRecebimento.getText();
       return new Fornecedor(auxNameFornecedor, auxNumFornecedor, 
               auxCNPJ, auxEmissao, auxRecebimento);
    }
    
    private void limparTexto(){
        campoNameFornecedor.setText("");
        campoNumeroFornecedor.setText("");
        campoCnpjFornecedor.setText("");
        campoDataEmissao.setText("");
        campoDataRecebimento.setText("");
    }
    private void resetTimer(){
        campoTime.setText("00:00:00");
        campoDate.setText("00/00/0000");
    }
    private MultiPainel() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        buttonSaveFornecedor = new javax.swing.JButton();
        buttonClearFornecedor = new javax.swing.JButton();
        campoNumeroFornecedor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        campoNameFornecedor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        listaNomeFornecedor = new javax.swing.JComboBox<>();
        listaStatusFornecedor = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        campoCnpjFornecedor = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        campoDataEmissao = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        campoDataRecebimento = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        playTime = new javax.swing.JButton();
        pauseTime = new javax.swing.JButton();
        resetTime = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        campoTime = new javax.swing.JTextField();
        campoDate = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        buttonCadastrarUsuario = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        buttonCloseMultiPainel = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PMSYS v0.1");
        setResizable(false);
        setSize(new java.awt.Dimension(1920, 1080));

        jTabbedPane1.setBackground(new java.awt.Color(1, 45, 69));
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(606, 383));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(606, 383));
        jTabbedPane1.setRequestFocusEnabled(false);

        jPanel1.setBackground(new java.awt.Color(1, 45, 69));
        jPanel1.setToolTipText("");
        jPanel1.setPreferredSize(new java.awt.Dimension(556, 410));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Aveline", 1, 100)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadEuroChem/img/logoIcon.png"))); // NOI18N
        jLabel1.setText("PMSYS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 108, 468, 144));

        jLabel2.setFont(new java.awt.Font("Aveline", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("V0.3");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 180, 96, 36));

        jTabbedPane1.addTab("HOME", jPanel1);

        jPanel2.setBackground(new java.awt.Color(1, 45, 69));
        jPanel2.setMinimumSize(new java.awt.Dimension(606, 383));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonSaveFornecedor.setBackground(new java.awt.Color(0, 255, 0));
        buttonSaveFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadEuroChem/img/inco1.png"))); // NOI18N
        buttonSaveFornecedor.setMaximumSize(new java.awt.Dimension(98, 74));
        buttonSaveFornecedor.setMinimumSize(new java.awt.Dimension(98, 74));
        buttonSaveFornecedor.setPreferredSize(new java.awt.Dimension(98, 74));
        buttonSaveFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveFornecedorActionPerformed(evt);
            }
        });
        jPanel2.add(buttonSaveFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 552, 132, 61));

        buttonClearFornecedor.setBackground(new java.awt.Color(255, 255, 51));
        buttonClearFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadEuroChem/img/imgClear.png"))); // NOI18N
        buttonClearFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearFornecedorActionPerformed(evt);
            }
        });
        jPanel2.add(buttonClearFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 552, 132, 61));

        campoNumeroFornecedor.setBackground(new java.awt.Color(255, 255, 255));
        campoNumeroFornecedor.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jPanel2.add(campoNumeroFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 420, 36));

        jLabel6.setFont(new java.awt.Font("Aveline", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("NOME:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 192, -1, -1));

        jLabel7.setFont(new java.awt.Font("Aveline", 1, 80)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("DADOS DO FORNECEDOR");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 60, -1, -1));

        jLabel8.setFont(new java.awt.Font("Aveline", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("NÚMERO:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 252, -1, 24));

        campoNameFornecedor.setBackground(new java.awt.Color(255, 255, 255));
        campoNameFornecedor.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jPanel2.add(campoNameFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 420, 36));

        jLabel10.setFont(new java.awt.Font("Aveline", 0, 28)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("FORNECEDORES CADASTRADOS");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(888, 180, -1, -1));

        jLabel11.setFont(new java.awt.Font("Aveline", 0, 28)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("NOME");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(888, 240, -1, -1));

        jLabel12.setFont(new java.awt.Font("Aveline", 0, 28)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("STATUS");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 240, -1, -1));

        listaNomeFornecedor.setBackground(new java.awt.Color(255, 255, 255));
        listaNomeFornecedor.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        listaNomeFornecedor.setForeground(new java.awt.Color(1, 45, 69));
        listaNomeFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaNomeFornecedorActionPerformed(evt);
            }
        });
        jPanel2.add(listaNomeFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(816, 288, 228, 36));

        listaStatusFornecedor.setBackground(new java.awt.Color(255, 255, 255));
        listaStatusFornecedor.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        listaStatusFornecedor.setForeground(new java.awt.Color(1, 45, 69));
        listaStatusFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaStatusFornecedorActionPerformed(evt);
            }
        });
        jPanel2.add(listaStatusFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 288, 228, 36));

        jLabel21.setFont(new java.awt.Font("Aveline", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("CNPJ:");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 312, 108, -1));

        campoCnpjFornecedor.setBackground(new java.awt.Color(255, 255, 255));
        campoCnpjFornecedor.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        campoCnpjFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCnpjFornecedorActionPerformed(evt);
            }
        });
        jPanel2.add(campoCnpjFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 420, 36));

        jLabel22.setFont(new java.awt.Font("Aveline", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("DATA EMISSÃO:");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 372, -1, -1));

        campoDataEmissao.setBackground(new java.awt.Color(255, 255, 255));
        campoDataEmissao.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        campoDataEmissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDataEmissaoActionPerformed(evt);
            }
        });
        jPanel2.add(campoDataEmissao, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 420, 36));

        jLabel23.setFont(new java.awt.Font("Aveline", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("RECEBIMENTO:");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 432, -1, -1));

        campoDataRecebimento.setBackground(new java.awt.Color(255, 255, 255));
        campoDataRecebimento.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        campoDataRecebimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDataRecebimentoActionPerformed(evt);
            }
        });
        jPanel2.add(campoDataRecebimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 420, 36));

        jTabbedPane1.addTab("FORNECEDOR", jPanel2);

        jPanel3.setBackground(new java.awt.Color(1, 45, 69));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Aveline", 1, 63)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TIME:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 204, 228, -1));

        jLabel5.setFont(new java.awt.Font("Aveline", 1, 63)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DATE:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 288, 228, 72));

        playTime.setBackground(new java.awt.Color(51, 51, 51));
        playTime.setForeground(new java.awt.Color(0, 0, 0));
        playTime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadEuroChem/img/icons8-reproduzir-96.png"))); // NOI18N
        jPanel3.add(playTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 540, 180, 96));

        pauseTime.setBackground(new java.awt.Color(51, 51, 51));
        pauseTime.setForeground(new java.awt.Color(0, 0, 0));
        pauseTime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadEuroChem/img/icons8-parar-96.png"))); // NOI18N
        jPanel3.add(pauseTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 540, 180, 96));

        resetTime.setBackground(new java.awt.Color(51, 51, 51));
        resetTime.setForeground(new java.awt.Color(0, 0, 0));
        resetTime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadEuroChem/img/icons8-compromisso-recorrente-96.png"))); // NOI18N
        resetTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetTimeActionPerformed(evt);
            }
        });
        jPanel3.add(resetTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(996, 540, 180, 96));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Aveline", 1, 63)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("NÚMERO:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 120, -1, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Aveline", 1, 63)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("NOME:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 36, -1, -1));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 48, 720, 48));

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 132, 720, 48));

        campoTime.setBackground(new java.awt.Color(255, 255, 255));
        campoTime.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jPanel3.add(campoTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 216, 720, 48));

        campoDate.setBackground(new java.awt.Color(255, 255, 255));
        campoDate.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jPanel3.add(campoDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 300, 720, 48));

        jLabel24.setFont(new java.awt.Font("Aveline", 1, 65)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("CNPJ:");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 372, -1, -1));

        jTextField13.setBackground(new java.awt.Color(255, 255, 255));
        jTextField13.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jPanel3.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 384, 720, 48));

        jTabbedPane1.addTab("TEMPO", jPanel3);

        jPanel5.setBackground(new java.awt.Color(1, 45, 69));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Aveline", 1, 80)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("INFORMAÇÕES DE USUÁRIO");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 35, 1097, 108));

        jLabel16.setFont(new java.awt.Font("Aveline", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("NOME:");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 214, -1, -1));

        jLabel17.setFont(new java.awt.Font("Aveline", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("EMAIL:");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 271, -1, -1));

        jLabel18.setFont(new java.awt.Font("Aveline", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("SENHA:");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 328, 122, -1));

        jTextField5.setBackground(new java.awt.Color(255, 255, 255));
        jTextField5.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel5.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 204, 456, 31));

        jTextField6.setBackground(new java.awt.Color(255, 255, 255));
        jTextField6.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel5.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 264, 456, 34));

        jTextField7.setBackground(new java.awt.Color(255, 255, 255));
        jTextField7.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel5.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 324, 456, 31));

        jButton1.setBackground(new java.awt.Color(0, 255, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadEuroChem/img/inco1.png"))); // NOI18N
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 558, 130, 70));

        jButton2.setBackground(new java.awt.Color(255, 255, 51));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadEuroChem/img/imgClear.png"))); // NOI18N
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(912, 552, 130, 70));

        jLabel19.setFont(new java.awt.Font("Aveline", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("TELEFONE:");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 384, -1, -1));

        jTextField8.setBackground(new java.awt.Color(255, 255, 255));
        jTextField8.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(0, 0, 0));
        jPanel5.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 384, 456, 31));

        jLabel20.setFont(new java.awt.Font("Aveline", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("CARGO:");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 444, 122, -1));

        jTextField9.setBackground(new java.awt.Color(255, 255, 255));
        jTextField9.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(0, 0, 0));
        jPanel5.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 444, 456, 31));

        jTabbedPane1.addTab("USUÁRIO", jPanel5);

        jPanel6.setBackground(new java.awt.Color(1, 45, 69));

        buttonCadastrarUsuario.setBackground(new java.awt.Color(0, 255, 0));
        buttonCadastrarUsuario.setFont(new java.awt.Font("Aveline", 1, 36)); // NOI18N
        buttonCadastrarUsuario.setForeground(new java.awt.Color(0, 0, 0));
        buttonCadastrarUsuario.setText("CADASTRAR");
        buttonCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarUsuarioActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Aveline", 1, 80)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CADASTRAR USUÁRIO");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(596, 596, 596)
                        .addComponent(buttonCadastrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 889, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(buttonCadastrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CADASTRO", jPanel6);

        jPanel4.setBackground(new java.awt.Color(1, 45, 69));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonCloseMultiPainel.setBackground(new java.awt.Color(255, 51, 51));
        buttonCloseMultiPainel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadEuroChem/img/return.png"))); // NOI18N
        buttonCloseMultiPainel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCloseMultiPainelActionPerformed(evt);
            }
        });
        jPanel4.add(buttonCloseMultiPainel, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 432, 330, 74));

        jLabel9.setFont(new java.awt.Font("Aveline", 1, 80)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ATÉ LOGO!");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 144, 504, 72));

        jTabbedPane1.addTab("SAIR", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1451, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCloseMultiPainelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseMultiPainelActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_buttonCloseMultiPainelActionPerformed
/*
    private void buttonClearFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearFornecedorActionPerformed
    }//GEN-LAST:event_buttonClearFornecedorActionPerformed
*/
    private void buttonCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCadastrarUsuarioActionPerformed
    //>>>>>> PAINEL FORNECEDOR <<<<<<<<<<
    private void buttonSaveFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveFornecedorActionPerformed
        // TODO add your handling code here:
        Fornecedor novoFornecedor = getCadastroFornecedor();
        fornecedores.add(novoFornecedor);
        limparTexto();
        System.out.println("FORNECEDOR: " + novoFornecedor.getNameFornecedor() +
                "\nNUMERO: " + novoFornecedor.getNumeroFornecedor() + 
                "\nCNPJ: " + novoFornecedor.getNumeroCnpj() + 
                "\nEMISSAO: " + novoFornecedor.getDateEmissao() + 
                "\nRECEBIMENTO: " + novoFornecedor.getDataRecebimento());
        
        JOptionPane.showMessageDialog(this, "SALVO COM SUCESSO!");
        JOptionPane.showMessageDialog(this, "\nFORNECEDOR: " + novoFornecedor.getNameFornecedor() + 
                "\nNUMERO: " + novoFornecedor.getNumeroFornecedor() + "\nCNPJ: " + novoFornecedor.getNumeroCnpj() + 
                "\nEMISSAO: " + novoFornecedor.getDateEmissao() + "\nRECEBIMENTO: " + novoFornecedor.getDataRecebimento());
        
        listaNomeFornecedor.addItem(novoFornecedor.getNameFornecedor());
        listaStatusFornecedor.addItem(novoFornecedor.getDataRecebimento());
    }//GEN-LAST:event_buttonSaveFornecedorActionPerformed

    private void campoCnpjFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCnpjFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCnpjFornecedorActionPerformed

    private void campoDataEmissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDataEmissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDataEmissaoActionPerformed

    private void campoDataRecebimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDataRecebimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDataRecebimentoActionPerformed

    private void listaNomeFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaNomeFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaNomeFornecedorActionPerformed

    private void resetTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetTimeActionPerformed
        // TODO add your handling code here:
        resetTimer();
    }//GEN-LAST:event_resetTimeActionPerformed

    private void listaStatusFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaStatusFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaStatusFornecedorActionPerformed
    
    private void buttonClearFornecedorActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
        limparTexto();
    }                 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultiPainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultiPainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultiPainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultiPainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MultiPainel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCadastrarUsuario;
    private javax.swing.JButton buttonClearFornecedor;
    private javax.swing.JButton buttonCloseMultiPainel;
    private javax.swing.JButton buttonSaveFornecedor;
    private javax.swing.JTextField campoCnpjFornecedor;
    private javax.swing.JTextField campoDataEmissao;
    private javax.swing.JTextField campoDataRecebimento;
    private javax.swing.JTextField campoDate;
    private javax.swing.JTextField campoNameFornecedor;
    private javax.swing.JTextField campoNumeroFornecedor;
    private javax.swing.JTextField campoTime;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JComboBox<String> listaNomeFornecedor;
    private javax.swing.JComboBox<String> listaStatusFornecedor;
    private javax.swing.JButton pauseTime;
    private javax.swing.JButton playTime;
    private javax.swing.JButton resetTime;
    // End of variables declaration//GEN-END:variables
}
